version: "3.8"

services:
  app:
    build: .
    container_name: wallet_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wallet_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      JWT_SECRET: supersecret
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
