# Usar uma imagem oficial do Node.js
FROM node:18

# Diretório de trabalho no contêiner
WORKDIR /app

# Copiar os arquivos package.json e package-lock.json
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante do código
COPY . .

# Expor a porta da aplicação
EXPOSE 3000

# Comando padrão para rodar o servidor
CMD ["npm", "run", "dev"]
